apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: my-java-app
          image: garstiops/garstiges-secret-repo:java-mysql-app-1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: java-app-ingress
spec:
  rules:
    - host: 143-42-223-129.ip.linodeusercontent.com
      http:
        paths:
          - backend:
              service:
                name: java-app-service
                port:
                  number: 8080
            pathType: Prefix
            path: /
