- name: Create Ec2-Instance
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    key_name: "{{ key_name }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    instance_type: "{{ instance_type }}"
    security_group: "{{ security_group }}"
    network:
      assign_public_ip: "{{ assign_public_ip }}"
    image_id: "{{ image_id }}"
    tags:
      Name: "{{environment}} {{instance_name}}"
